// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/product.proto
// Protobuf Java Version: 4.26.0

package com.aspiresys.protobufdemo.entity;

public final class Product {
  private Product() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      Product.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface productOrBuilder extends
      // @@protoc_insertion_point(interface_extends:product.product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string price = 3;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 3;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();
  }
  /**
   * Protobuf type {@code product.product}
   */
  public static final class product extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:product.product)
      productOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        product.class.getName());
    }
    // Use product.newBuilder() to construct.
    private product(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private product() {
      title_ = "";
      description_ = "";
      price_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aspiresys.protobufdemo.entity.Product.internal_static_product_product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aspiresys.protobufdemo.entity.Product.internal_static_product_product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aspiresys.protobufdemo.entity.Product.product.class, com.aspiresys.protobufdemo.entity.Product.product.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object price_ = "";
    /**
     * <code>string price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 3;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, price_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aspiresys.protobufdemo.entity.Product.product)) {
        return super.equals(obj);
      }
      com.aspiresys.protobufdemo.entity.Product.product other = (com.aspiresys.protobufdemo.entity.Product.product) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aspiresys.protobufdemo.entity.Product.product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.aspiresys.protobufdemo.entity.Product.product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.aspiresys.protobufdemo.entity.Product.product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aspiresys.protobufdemo.entity.Product.product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code product.product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:product.product)
        com.aspiresys.protobufdemo.entity.Product.productOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aspiresys.protobufdemo.entity.Product.product.class, com.aspiresys.protobufdemo.entity.Product.product.Builder.class);
      }

      // Construct using com.aspiresys.protobufdemo.entity.Product.product.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        title_ = "";
        description_ = "";
        price_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_product_descriptor;
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.product getDefaultInstanceForType() {
        return com.aspiresys.protobufdemo.entity.Product.product.getDefaultInstance();
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.product build() {
        com.aspiresys.protobufdemo.entity.Product.product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.product buildPartial() {
        com.aspiresys.protobufdemo.entity.Product.product result = new com.aspiresys.protobufdemo.entity.Product.product(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.aspiresys.protobufdemo.entity.Product.product result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.price_ = price_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aspiresys.protobufdemo.entity.Product.product) {
          return mergeFrom((com.aspiresys.protobufdemo.entity.Product.product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aspiresys.protobufdemo.entity.Product.product other) {
        if (other == com.aspiresys.protobufdemo.entity.Product.product.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                price_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 3;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        price_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        price_ = getDefaultInstance().getPrice();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        price_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:product.product)
    }

    // @@protoc_insertion_point(class_scope:product.product)
    private static final com.aspiresys.protobufdemo.entity.Product.product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aspiresys.protobufdemo.entity.Product.product();
    }

    public static com.aspiresys.protobufdemo.entity.Product.product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<product>
        PARSER = new com.google.protobuf.AbstractParser<product>() {
      @java.lang.Override
      public product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aspiresys.protobufdemo.entity.Product.product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface prodcutListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:product.prodcutList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    java.util.List<com.aspiresys.protobufdemo.entity.Product.product> 
        getProductListList();
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    com.aspiresys.protobufdemo.entity.Product.product getProductList(int index);
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    int getProductListCount();
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    java.util.List<? extends com.aspiresys.protobufdemo.entity.Product.productOrBuilder> 
        getProductListOrBuilderList();
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    com.aspiresys.protobufdemo.entity.Product.productOrBuilder getProductListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code product.prodcutList}
   */
  public static final class prodcutList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:product.prodcutList)
      prodcutListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        prodcutList.class.getName());
    }
    // Use prodcutList.newBuilder() to construct.
    private prodcutList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private prodcutList() {
      productList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aspiresys.protobufdemo.entity.Product.internal_static_product_prodcutList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aspiresys.protobufdemo.entity.Product.internal_static_product_prodcutList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aspiresys.protobufdemo.entity.Product.prodcutList.class, com.aspiresys.protobufdemo.entity.Product.prodcutList.Builder.class);
    }

    public static final int PRODUCTLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.aspiresys.protobufdemo.entity.Product.product> productList_;
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.aspiresys.protobufdemo.entity.Product.product> getProductListList() {
      return productList_;
    }
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.aspiresys.protobufdemo.entity.Product.productOrBuilder> 
        getProductListOrBuilderList() {
      return productList_;
    }
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    @java.lang.Override
    public int getProductListCount() {
      return productList_.size();
    }
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    @java.lang.Override
    public com.aspiresys.protobufdemo.entity.Product.product getProductList(int index) {
      return productList_.get(index);
    }
    /**
     * <code>repeated .product.product productList = 1;</code>
     */
    @java.lang.Override
    public com.aspiresys.protobufdemo.entity.Product.productOrBuilder getProductListOrBuilder(
        int index) {
      return productList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < productList_.size(); i++) {
        output.writeMessage(1, productList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < productList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, productList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aspiresys.protobufdemo.entity.Product.prodcutList)) {
        return super.equals(obj);
      }
      com.aspiresys.protobufdemo.entity.Product.prodcutList other = (com.aspiresys.protobufdemo.entity.Product.prodcutList) obj;

      if (!getProductListList()
          .equals(other.getProductListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductListCount() > 0) {
        hash = (37 * hash) + PRODUCTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getProductListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.aspiresys.protobufdemo.entity.Product.prodcutList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aspiresys.protobufdemo.entity.Product.prodcutList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code product.prodcutList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:product.prodcutList)
        com.aspiresys.protobufdemo.entity.Product.prodcutListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_prodcutList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_prodcutList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aspiresys.protobufdemo.entity.Product.prodcutList.class, com.aspiresys.protobufdemo.entity.Product.prodcutList.Builder.class);
      }

      // Construct using com.aspiresys.protobufdemo.entity.Product.prodcutList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (productListBuilder_ == null) {
          productList_ = java.util.Collections.emptyList();
        } else {
          productList_ = null;
          productListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aspiresys.protobufdemo.entity.Product.internal_static_product_prodcutList_descriptor;
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.prodcutList getDefaultInstanceForType() {
        return com.aspiresys.protobufdemo.entity.Product.prodcutList.getDefaultInstance();
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.prodcutList build() {
        com.aspiresys.protobufdemo.entity.Product.prodcutList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aspiresys.protobufdemo.entity.Product.prodcutList buildPartial() {
        com.aspiresys.protobufdemo.entity.Product.prodcutList result = new com.aspiresys.protobufdemo.entity.Product.prodcutList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.aspiresys.protobufdemo.entity.Product.prodcutList result) {
        if (productListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            productList_ = java.util.Collections.unmodifiableList(productList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.productList_ = productList_;
        } else {
          result.productList_ = productListBuilder_.build();
        }
      }

      private void buildPartial0(com.aspiresys.protobufdemo.entity.Product.prodcutList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aspiresys.protobufdemo.entity.Product.prodcutList) {
          return mergeFrom((com.aspiresys.protobufdemo.entity.Product.prodcutList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aspiresys.protobufdemo.entity.Product.prodcutList other) {
        if (other == com.aspiresys.protobufdemo.entity.Product.prodcutList.getDefaultInstance()) return this;
        if (productListBuilder_ == null) {
          if (!other.productList_.isEmpty()) {
            if (productList_.isEmpty()) {
              productList_ = other.productList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductListIsMutable();
              productList_.addAll(other.productList_);
            }
            onChanged();
          }
        } else {
          if (!other.productList_.isEmpty()) {
            if (productListBuilder_.isEmpty()) {
              productListBuilder_.dispose();
              productListBuilder_ = null;
              productList_ = other.productList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductListFieldBuilder() : null;
            } else {
              productListBuilder_.addAllMessages(other.productList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.aspiresys.protobufdemo.entity.Product.product m =
                    input.readMessage(
                        com.aspiresys.protobufdemo.entity.Product.product.parser(),
                        extensionRegistry);
                if (productListBuilder_ == null) {
                  ensureProductListIsMutable();
                  productList_.add(m);
                } else {
                  productListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.aspiresys.protobufdemo.entity.Product.product> productList_ =
        java.util.Collections.emptyList();
      private void ensureProductListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          productList_ = new java.util.ArrayList<com.aspiresys.protobufdemo.entity.Product.product>(productList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.aspiresys.protobufdemo.entity.Product.product, com.aspiresys.protobufdemo.entity.Product.product.Builder, com.aspiresys.protobufdemo.entity.Product.productOrBuilder> productListBuilder_;

      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public java.util.List<com.aspiresys.protobufdemo.entity.Product.product> getProductListList() {
        if (productListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productList_);
        } else {
          return productListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public int getProductListCount() {
        if (productListBuilder_ == null) {
          return productList_.size();
        } else {
          return productListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public com.aspiresys.protobufdemo.entity.Product.product getProductList(int index) {
        if (productListBuilder_ == null) {
          return productList_.get(index);
        } else {
          return productListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder setProductList(
          int index, com.aspiresys.protobufdemo.entity.Product.product value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.set(index, value);
          onChanged();
        } else {
          productListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder setProductList(
          int index, com.aspiresys.protobufdemo.entity.Product.product.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.set(index, builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder addProductList(com.aspiresys.protobufdemo.entity.Product.product value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.add(value);
          onChanged();
        } else {
          productListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder addProductList(
          int index, com.aspiresys.protobufdemo.entity.Product.product value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.add(index, value);
          onChanged();
        } else {
          productListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder addProductList(
          com.aspiresys.protobufdemo.entity.Product.product.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.add(builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder addProductList(
          int index, com.aspiresys.protobufdemo.entity.Product.product.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.add(index, builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder addAllProductList(
          java.lang.Iterable<? extends com.aspiresys.protobufdemo.entity.Product.product> values) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, productList_);
          onChanged();
        } else {
          productListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder clearProductList() {
        if (productListBuilder_ == null) {
          productList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public Builder removeProductList(int index) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.remove(index);
          onChanged();
        } else {
          productListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public com.aspiresys.protobufdemo.entity.Product.product.Builder getProductListBuilder(
          int index) {
        return getProductListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public com.aspiresys.protobufdemo.entity.Product.productOrBuilder getProductListOrBuilder(
          int index) {
        if (productListBuilder_ == null) {
          return productList_.get(index);  } else {
          return productListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public java.util.List<? extends com.aspiresys.protobufdemo.entity.Product.productOrBuilder> 
           getProductListOrBuilderList() {
        if (productListBuilder_ != null) {
          return productListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productList_);
        }
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public com.aspiresys.protobufdemo.entity.Product.product.Builder addProductListBuilder() {
        return getProductListFieldBuilder().addBuilder(
            com.aspiresys.protobufdemo.entity.Product.product.getDefaultInstance());
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public com.aspiresys.protobufdemo.entity.Product.product.Builder addProductListBuilder(
          int index) {
        return getProductListFieldBuilder().addBuilder(
            index, com.aspiresys.protobufdemo.entity.Product.product.getDefaultInstance());
      }
      /**
       * <code>repeated .product.product productList = 1;</code>
       */
      public java.util.List<com.aspiresys.protobufdemo.entity.Product.product.Builder> 
           getProductListBuilderList() {
        return getProductListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.aspiresys.protobufdemo.entity.Product.product, com.aspiresys.protobufdemo.entity.Product.product.Builder, com.aspiresys.protobufdemo.entity.Product.productOrBuilder> 
          getProductListFieldBuilder() {
        if (productListBuilder_ == null) {
          productListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.aspiresys.protobufdemo.entity.Product.product, com.aspiresys.protobufdemo.entity.Product.product.Builder, com.aspiresys.protobufdemo.entity.Product.productOrBuilder>(
                  productList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          productList_ = null;
        }
        return productListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:product.prodcutList)
    }

    // @@protoc_insertion_point(class_scope:product.prodcutList)
    private static final com.aspiresys.protobufdemo.entity.Product.prodcutList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aspiresys.protobufdemo.entity.Product.prodcutList();
    }

    public static com.aspiresys.protobufdemo.entity.Product.prodcutList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<prodcutList>
        PARSER = new com.google.protobuf.AbstractParser<prodcutList>() {
      @java.lang.Override
      public prodcutList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<prodcutList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<prodcutList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aspiresys.protobufdemo.entity.Product.prodcutList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_product_product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_prodcutList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_product_prodcutList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/product.proto\022\007product\"<\n\007pr" +
      "oduct\022\r\n\005title\030\001 \001(\t\022\023\n\013description\030\002 \001(" +
      "\t\022\r\n\005price\030\003 \001(\t\"4\n\013prodcutList\022%\n\013produ" +
      "ctList\030\001 \003(\0132\020.product.productB,\n!com.as" +
      "piresys.protobufdemo.entityB\007Productb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_product_product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_product_product_descriptor,
        new java.lang.String[] { "Title", "Description", "Price", });
    internal_static_product_prodcutList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_prodcutList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_product_prodcutList_descriptor,
        new java.lang.String[] { "ProductList", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
